server:
  port: 8083

spring:
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver:
      class: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
